/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ManualDepth, ModeConfig, ModeId, Question, QuestionOption } from "./schemaTypes";

function option(value: string, label: string, manualMeaning?: string): QuestionOption {
  return { value, label, manualMeaning };
}

export function getOptionValue(item: string | QuestionOption): string {
  return typeof item === "string" ? item : item.value;
}

export function getOptionLabel(item: string | QuestionOption): string {
  return typeof item === "string" ? item : item.label;
}

export function getOptionManualMeaning(item: string | QuestionOption): string {
  if (typeof item === "string") return item;
  return item.manualMeaning || item.label;
}

export function findQuestionOption(question: Question, value: string): string | QuestionOption | undefined {
  return question.options?.find((item) => getOptionValue(item) === value || getOptionLabel(item) === value);
}

export function getModeConfigForDepth(mode: ModeId, depth: ManualDepth = "manual"): ModeConfig {
  const config = PROTOCOL_MANIFEST[mode];
  const questions = selectQuestionsForDepth(config.questions, depth);
  const activeSectionIds = new Set(questions.map((question) => question.sectionId));

  return {
    ...config,
    sections: config.sections.filter((section) => activeSectionIds.has(section.id)),
    questions,
  };
}

function selectQuestionsForDepth(questions: Question[], depth: ManualDepth): Question[] {
  if (depth === "deep") return questions;

  const mvpQuestions = questions.filter((question) => question.depth === "mvp");
  if (depth === "manual") return mvpQuestions;

  return [...mvpQuestions]
    .sort((a, b) => (a.priority ?? Number.POSITIVE_INFINITY) - (b.priority ?? Number.POSITIVE_INFINITY))
    .slice(0, 5);
}

const supportOptions = [
  option("listen", "Listen without fixing", "listen without immediately fixing it"),
  option("practical_help", "Offer practical help", "offer practical help"),
  option("quiet_company", "Stay nearby quietly", "stay nearby quietly"),
  option("space", "Give me space", "give me space"),
  option("distract", "Offer a small distraction", "offer a small distraction"),
];

const repairOptions = [
  option("clear_apology", "A clear apology", "a clear apology"),
  option("time_then_return", "Time, then a return to the topic", "time to settle, followed by a return to the topic"),
  option("specific_next_step", "A specific next step", "a specific next step"),
  option("reassurance", "Reassurance of care", "reassurance that the relationship is still steady"),
  option("own_the_part", "Each person naming their part", "each person naming their part"),
];

const directnessOptions = [
  option("direct_private", "Tell me directly and privately", "direct private feedback"),
  option("context_first", "Start with context, then be direct", "context first, then direct feedback"),
  option("written_first", "Send it in writing first", "written feedback before live discussion"),
  option("ask_permission", "Ask if I have capacity first", "a capacity check before feedback"),
];

export const PROTOCOL_MANIFEST: Record<ModeId, ModeConfig> = {
  me: {
    id: "me",
    name: "Me Manual",
    label: "How to understand me",
    description: "Write the things people should know before they guess wrong.",
    theme: "me",
    sections: [
      { id: "connection", title: "Connection", description: "How care and attention reach me." },
      { id: "communication", title: "Communication", description: "How I process, ask, and respond." },
      { id: "boundaries", title: "Boundaries", description: "What helps closeness stay respectful." },
      { id: "tension", title: "Tension", description: "How to slow down and repair." },
      { id: "rhythm", title: "Rhythm", description: "Energy, attention, and everyday pacing." },
    ],
    questions: [
      { id: "M_M_01", mode: "me", sectionId: "connection", depth: "mvp", priority: 3, dimension: "Care and support", type: "multiSelect", options: supportOptions, label: "When you are going through a difficult time, what support actually helps?", defaultVisibility: "share", manualTemplate: "When I am having a difficult time, it helps if you {answer}." },
      { id: "M_M_02", mode: "me", sectionId: "tension", depth: "mvp", priority: 1, dimension: "Stress response", type: "select", options: [option("quiet", "I go quiet", "go quiet and need more room"), option("faster", "I talk faster", "talk faster and need us to slow down"), option("leave", "I need to step away", "need to step away before continuing"), option("explain", "I over-explain", "over-explain because I am trying to be understood")], label: "During a heated moment, what do you usually do when you feel overwhelmed?", defaultVisibility: "private", manualTemplate: "When I feel overwhelmed, I may {answer}." },
      { id: "M_M_03", mode: "me", sectionId: "tension", depth: "mvp", priority: 2, dimension: "Repair needs", type: "multiSelect", options: repairOptions, label: "After tension, what helps you feel ready to reconnect?", defaultVisibility: "private", manualTemplate: "After tension, reconnection is easier with {answer}." },
      { id: "M_M_04", mode: "me", sectionId: "rhythm", depth: "mvp", priority: 8, dimension: "Social energy", type: "select", options: [option("steady", "I stay steady for a long time", "extended time can feel steady for me"), option("selective", "I have energy for the right setting", "my energy depends on the setting"), option("shorter", "I do better with shorter time together", "shorter time together helps me stay present"), option("recover", "I need recovery time afterward", "I may need recovery time afterward")], label: "How does your energy usually work during extended time with friends or family?", defaultVisibility: "share", manualTemplate: "In extended time together, {answer}." },
      { id: "M_M_05", mode: "me", sectionId: "connection", depth: "mvp", priority: 5, dimension: "Connection bids", type: "text", label: "When you want attention or affection but have trouble asking, what might someone notice?", defaultVisibility: "private", manualTemplate: "When I want connection but have trouble asking, you might notice {answer}." },
      { id: "M_M_06", mode: "me", sectionId: "communication", depth: "mvp", priority: 6, dimension: "Misread patterns", type: "textarea", label: "What do people sometimes misread about you?", defaultVisibility: "private", manualTemplate: "People sometimes misread {answer}. Please ask before assuming." },
      { id: "M_M_07", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 9, dimension: "Digital boundaries", type: "select", options: [option("text_first", "Text first", "text first before calling"), option("calls_ok", "Calls are usually okay", "calls are usually okay"), option("urgent_only", "Call only for something time-sensitive", "call only for time-sensitive things"), option("ask_first", "Ask before calling", "ask before calling")], label: "How do you feel about unplanned phone calls from people close to you?", defaultVisibility: "share", manualTemplate: "For unplanned calls, please {answer}." },
      { id: "M_M_08", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 10, dimension: "Closeness and autonomy", type: "scale", min: 1, max: 5, helperText: "1 = More independent time, 5 = More shared time", label: "In close relationships, how much independent time versus shared time helps you feel steady?", defaultVisibility: "private", manualTemplate: "For independent time versus shared time, I am around {answer} on a 1 to 5 scale." },
      { id: "M_M_09", mode: "me", sectionId: "tension", depth: "mvp", priority: 7, dimension: "Pacing", type: "select", options: [option("same_day", "Usually the same day", "raise concerns the same day when possible"), option("after_time", "After I have had time", "need time before raising concerns"), option("written", "I write first", "often write before talking"), option("hard_to_raise", "I find it hard to raise", "may need an invitation to name concerns")], label: "When someone close to you does something upsetting, how soon do you usually bring it up?", defaultVisibility: "private", manualTemplate: "When something upsets me, I usually {answer}." },
      { id: "M_M_10", mode: "me", sectionId: "communication", depth: "mvp", priority: 4, dimension: "Processing style", type: "select", options: [option("write_first", "Write first", "write first"), option("talk_live", "Talk it through live", "talk it through live"), option("pause", "Pause before answering", "pause before answering"), option("question_first", "Start with one clear question", "start with one clear question")], label: "When something matters, how do you prefer to process it?", defaultVisibility: "share", manualTemplate: "When something matters, I process best when I can {answer}." },
      { id: "M_M_11", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 11, dimension: "Consent and boundaries", type: "textarea", label: "What is one boundary that helps you stay open instead of guarded?", defaultVisibility: "private", manualTemplate: "One boundary that helps me stay open is {answer}." },
      { id: "M_M_12", mode: "me", sectionId: "connection", depth: "mvp", priority: 12, dimension: "Care expression", type: "multiSelect", options: [option("check_ins", "Small check-ins", "small check-ins"), option("practical_care", "Practical care", "practical care"), option("quality_time", "Focused time", "focused time"), option("thoughtful_words", "Thoughtful words", "thoughtful words"), option("respecting_space", "Respecting my space", "respecting my space")], label: "How do you most naturally notice that someone cares?", defaultVisibility: "share", manualTemplate: "I tend to notice care through {answer}." },
      { id: "M_D_01", mode: "me", sectionId: "connection", depth: "deep", dimension: "Support", type: "textarea", label: "What kind of help can feel well-meant but unhelpful?", defaultVisibility: "private", manualTemplate: "Well-meant help can be unhelpful when {answer}." },
      { id: "M_D_02", mode: "me", sectionId: "tension", depth: "deep", dimension: "Repair needs", type: "text", label: "If someone breaks a small promise, what helps make it right?", defaultVisibility: "private", manualTemplate: "If a small promise is broken, repair looks like {answer}." },
      { id: "M_D_03", mode: "me", sectionId: "communication", depth: "deep", dimension: "Directness", type: "pairedChoice", leftLabel: "Tell me plainly", rightLabel: "Warm me up first", label: "When something is difficult to hear, what helps it land?", defaultVisibility: "share", manualTemplate: "Difficult things land better when the approach is {answer}." },
      { id: "M_D_04", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Digital boundaries", type: "textarea", label: "What digital boundary would help people respect your attention?", defaultVisibility: "share", manualTemplate: "A digital boundary that helps me is {answer}." },
      { id: "M_D_05", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Recovery", type: "select", options: [option("quiet", "Quiet time", "quiet time"), option("movement", "Movement or a reset walk", "movement or a reset walk"), option("sleep", "Sleep or a full stop", "sleep or a full stop"), option("normal_routine", "A normal routine", "a normal routine")], label: "After a demanding day, what helps you come back to yourself?", defaultVisibility: "private", manualTemplate: "After a demanding day, I usually need {answer}." },
      { id: "M_D_06", mode: "me", sectionId: "communication", depth: "deep", dimension: "Listening cues", type: "textarea", label: "When you are listening carefully, what might your body language look like?", defaultVisibility: "share", manualTemplate: "When I am listening carefully, I may look like {answer}." },
      { id: "M_D_07", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Topic boundaries", type: "textarea", label: "What topic or setting needs extra permission before someone goes there with you?", defaultVisibility: "private", manualTemplate: "Please ask before bringing up {answer}." },
      { id: "M_D_08", mode: "me", sectionId: "connection", depth: "deep", dimension: "Appreciation", type: "text", label: "What is a small gesture that means more to you than people realize?", defaultVisibility: "share", manualTemplate: "A small gesture that means a lot to me is {answer}." },
      { id: "M_D_09", mode: "me", sectionId: "tension", depth: "deep", dimension: "Pause signals", type: "text", label: "What phrase could someone use when they notice the conversation needs to slow down?", defaultVisibility: "private", manualTemplate: "If we need to slow down, it helps to say: {answer}." },
      { id: "M_D_10", mode: "me", sectionId: "communication", depth: "deep", dimension: "Clarity", type: "multiSelect", options: [option("examples", "Specific examples", "specific examples"), option("one_topic", "One topic at a time", "one topic at a time"), option("plain_request", "A plain request", "a plain request"), option("time_to_reply", "Time to reply", "time to reply")], label: "What helps you understand a sensitive message clearly?", defaultVisibility: "share", manualTemplate: "Sensitive messages are easier for me with {answer}." },
      { id: "M_D_11", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Social pacing", type: "scale", min: 1, max: 5, helperText: "1 = Plans need notice, 5 = Spontaneous plans are easy", label: "How much notice helps you say yes to plans?", defaultVisibility: "share", manualTemplate: "For plans, my notice preference is around {answer} on a 1 to 5 scale." },
      { id: "M_D_12", mode: "me", sectionId: "connection", depth: "deep", dimension: "Receiving care", type: "textarea", label: "What makes care feel respectful rather than intrusive?", defaultVisibility: "private", manualTemplate: "Care feels respectful when {answer}." },
      { id: "M_D_13", mode: "me", sectionId: "tension", depth: "deep", dimension: "Accountability", type: "textarea", label: "When you need to apologize, what helps you do it honestly?", defaultVisibility: "private", manualTemplate: "When I need to apologize, it helps if {answer}." },
      { id: "M_D_14", mode: "me", sectionId: "communication", depth: "deep", dimension: "Assumptions", type: "textarea", label: "What should people ask about before they decide what your silence means?", defaultVisibility: "private", manualTemplate: "Before deciding what my silence means, please ask about {answer}." },
      { id: "M_D_15", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Physical boundaries", type: "textarea", label: "What personal-space preference should someone know before they try to comfort you?", defaultVisibility: "private", manualTemplate: "For personal space, it helps to know {answer}." },
      { id: "M_D_16", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Attention", type: "pairedChoice", leftLabel: "I like parallel time", rightLabel: "I like focused attention", label: "When spending time together, what kind of presence feels best?", defaultVisibility: "share", manualTemplate: "Time together feels best with {answer}." },
      { id: "M_D_17", mode: "me", sectionId: "connection", depth: "deep", dimension: "Requests", type: "text", label: "What is something you often need but forget to ask for?", defaultVisibility: "private", manualTemplate: "Something I may need but forget to ask for is {answer}." },
      { id: "M_D_18", mode: "me", sectionId: "communication", depth: "deep", dimension: "Tone", type: "textarea", label: "What tone helps you stay open during disagreement?", defaultVisibility: "share", manualTemplate: "During disagreement, I stay more open with {answer}." },
      { id: "M_D_19", mode: "me", sectionId: "tension", depth: "deep", dimension: "Repair timing", type: "select", options: [option("immediate", "Soon after", "soon after"), option("same_day", "Later the same day", "later the same day"), option("next_day", "After a night of rest", "after a night of rest"), option("scheduled", "At a planned time", "at a planned time")], label: "When repair is needed, what timing usually works best?", defaultVisibility: "private", manualTemplate: "Repair usually works best {answer}." },
      { id: "M_D_20", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Sharing boundaries", type: "textarea", label: "What should someone check with you before sharing about you with others?", defaultVisibility: "private", manualTemplate: "Please check with me before sharing {answer}." },
      { id: "M_D_21", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Transitions", type: "text", label: "What helps you transition from alone time into connection?", defaultVisibility: "share", manualTemplate: "I transition into connection more easily with {answer}." },
      { id: "M_D_22", mode: "me", sectionId: "connection", depth: "deep", dimension: "Encouragement", type: "textarea", label: "What kind of encouragement feels steadying instead of pressuring?", defaultVisibility: "share", manualTemplate: "Encouragement feels steadying when {answer}." },
      { id: "M_D_23", mode: "me", sectionId: "communication", depth: "deep", dimension: "Repair language", type: "text", label: "What sentence helps you feel someone is still with you during a hard talk?", defaultVisibility: "private", manualTemplate: "During a hard talk, it helps to hear: {answer}." },
      { id: "M_D_24", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Omitted is valid", type: "textarea", label: "What is something you prefer to keep out of a shared manual?", defaultVisibility: "hide", manualTemplate: "I prefer to omit {answer} from shared versions." },
    ],
  },
  work: {
    id: "work",
    name: "Work Manual",
    label: "How to work with me",
    description: "Share how you focus, decide, talk, and build trust.",
    theme: "work",
    sections: [
      { id: "communication", title: "Communication", description: "How information and feedback land best." },
      { id: "execution", title: "Execution", description: "How work moves from idea to done." },
      { id: "boundaries", title: "Boundaries", description: "Availability, attention, and handoff limits." },
      { id: "pressure", title: "Pressure", description: "Stress, urgency, and support." },
      { id: "culture", title: "Culture", description: "Trust, recognition, and team fit." },
    ],
    questions: [
      { id: "W_M_01", mode: "work", sectionId: "communication", depth: "mvp", priority: 4, dimension: "Processing style", type: "select", options: [option("pre_read", "A pre-read before live discussion", "a pre-read before live discussion"), option("live", "A live conversation", "a live conversation"), option("written", "A written brief", "a written brief"), option("hybrid", "A short brief, then a live check-in", "a short brief, then a live check-in")], label: "When dealing with complex new information, how do you prefer to digest it?", defaultVisibility: "share", manualTemplate: "For complex new information, please use {answer}." },
      { id: "W_M_02", mode: "work", sectionId: "communication", depth: "mvp", priority: 2, dimension: "Directness and context", type: "select", options: directnessOptions, label: "If there is a flaw in your idea, how should a teammate bring it up?", defaultVisibility: "share", manualTemplate: "If there is a flaw in my idea, feedback lands best as {answer}." },
      { id: "W_M_03", mode: "work", sectionId: "execution", depth: "mvp", priority: 9, dimension: "Autonomy and closeness", type: "select", options: [option("autonomy", "Give me the goal and room to own it", "a clear goal with room to own the path"), option("milestones", "Agree on milestones and check-ins", "milestones and check-ins"), option("collaborative", "Work closely with me as it takes shape", "close collaboration while it takes shape"), option("clear_brief", "Give me a detailed brief first", "a detailed brief before I start")], label: "What collaboration style helps you do your best work?", defaultVisibility: "share", manualTemplate: "I do my best work with {answer}." },
      { id: "W_M_04", mode: "work", sectionId: "boundaries", depth: "mvp", priority: 12, dimension: "Digital boundaries", type: "select", options: [option("next_day", "I will respond next working day", "respond next working day"), option("read_not_reply", "I may read, but not reply", "may read but not reply"), option("urgent_only", "Only urgent items need a response", "respond only when it is urgent"), option("clear_marker", "Mark urgency clearly", "need urgency marked clearly")], label: "How do you treat non-urgent digital messages outside working hours?", defaultVisibility: "share", manualTemplate: "For non-urgent messages outside working hours, I usually {answer}." },
      { id: "W_M_05", mode: "work", sectionId: "pressure", depth: "mvp", priority: 6, dimension: "Stress signals", type: "multiSelect", options: [option("quiet", "I get quieter", "get quieter"), option("rigid", "I get more rigid", "get more rigid"), option("overcommunicate", "I overcommunicate", "overcommunicate"), option("slow_reply", "I reply more slowly", "reply more slowly"), option("narrow_focus", "I narrow my focus", "narrow my focus")], label: "What is your most common behavioral tell when you are overwhelmed at work?", defaultVisibility: "private", manualTemplate: "When I am overwhelmed at work, I may {answer}." },
      { id: "W_M_06", mode: "work", sectionId: "pressure", depth: "mvp", priority: 7, dimension: "Care and support", type: "select", options: [option("prioritize", "Help me prioritize", "help me prioritize"), option("remove_blocker", "Remove or clarify a blocker", "remove or clarify a blocker"), option("quiet_space", "Give me quiet space", "give me quiet space"), option("check_capacity", "Ask what capacity I have", "ask what capacity I have")], label: "When that stress tell appears, what is the most useful response from a colleague?", defaultVisibility: "private", manualTemplate: "When that stress tell appears, the most useful response is to {answer}." },
      { id: "W_M_07", mode: "work", sectionId: "execution", depth: "mvp", priority: 10, dimension: "Attention and focus", type: "select", options: [option("long_blocks", "Long quiet blocks", "long quiet blocks"), option("short_sprints", "Short focused sprints", "short focused sprints"), option("meeting_days", "Meeting days and focus days separated", "meeting days and focus days separated"), option("flexible", "Flexible around the work", "flexible around the work")], label: "How do you prefer to structure your daily focus?", defaultVisibility: "share", manualTemplate: "My focus works best with {answer}." },
      { id: "W_M_08", mode: "work", sectionId: "communication", depth: "mvp", priority: 11, dimension: "Urgency and escalation", type: "text", label: "What is the best way to interrupt you for a genuine time-sensitive emergency?", defaultVisibility: "share", manualTemplate: "For a genuine time-sensitive emergency, reach me by {answer}." },
      { id: "W_M_09", mode: "work", sectionId: "culture", depth: "mvp", priority: 8, dimension: "Misread patterns", type: "textarea", label: "What is a common way your working style is misunderstood by people who do not know you well?", defaultVisibility: "private", manualTemplate: "People may misunderstand my working style as {answer}. Please ask before assuming." },
      { id: "W_M_10", mode: "work", sectionId: "execution", depth: "mvp", priority: 5, dimension: "Decision-making", type: "select", options: [option("data", "Clear data or examples", "clear data or examples"), option("owner", "A named decision owner", "a named decision owner"), option("consensus", "Enough group alignment", "enough group alignment"), option("reversible", "Knowing whether it is reversible", "knowing whether the decision is reversible")], label: "When a team decision needs to be made, what helps you move forward?", defaultVisibility: "share", manualTemplate: "I can move forward on team decisions when there is {answer}." },
      { id: "W_M_11", mode: "work", sectionId: "culture", depth: "mvp", priority: 11, dimension: "Recognition", type: "select", options: [option("private", "Private appreciation", "private appreciation"), option("public", "Public credit", "public credit"), option("specific", "Specific feedback on the work", "specific feedback on the work"), option("opportunity", "A meaningful next opportunity", "a meaningful next opportunity")], label: "When you do excellent work, how do you prefer to be recognized?", defaultVisibility: "share", manualTemplate: "Recognition is most meaningful to me as {answer}." },
      { id: "W_M_12", mode: "work", sectionId: "communication", depth: "mvp", priority: 3, dimension: "Meeting energy", type: "scale", min: 1, max: 5, helperText: "1 = Draining quickly, 5 = Usually energizing", label: "How do back-to-back video meetings usually affect your energy?", defaultVisibility: "share", manualTemplate: "Back-to-back video meetings affect my energy around {answer} on a 1 to 5 scale." },
      { id: "W_D_01", mode: "work", sectionId: "communication", depth: "deep", dimension: "Psychological safety", type: "textarea", label: "If you need to push back on leadership, what makes it feel possible to speak honestly?", defaultVisibility: "private", manualTemplate: "I can push back more honestly when {answer}." },
      { id: "W_D_02", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Accountability", type: "select", options: [option("fix_then_flag", "Bring the issue with a proposed fix", "bring the issue with a proposed fix"), option("flag_fast", "Flag it quickly", "flag it quickly"), option("ask_help", "Ask for help early", "ask for help early"), option("document", "Document what happened", "document what happened")], label: "When you make a mistake, what helps you handle it well?", defaultVisibility: "private", manualTemplate: "When I make a mistake, I handle it best when I can {answer}." },
      { id: "W_D_03", mode: "work", sectionId: "execution", depth: "deep", dimension: "Ambiguity", type: "select", options: [option("ask_questions", "Ask clarifying questions", "ask clarifying questions"), option("draft_options", "Draft options and get direction", "draft options and get direction"), option("start_small", "Start with a small version", "start with a small version"), option("pause", "Pause until the brief is clearer", "pause until the brief is clearer")], label: "How do you behave when project requirements are vague?", defaultVisibility: "share", manualTemplate: "When requirements are vague, I tend to {answer}." },
      { id: "W_D_04", mode: "work", sectionId: "boundaries", depth: "deep", dimension: "Availability", type: "pairedChoice", leftLabel: "Protect set hours", rightLabel: "Blend flexibly", label: "Do you prefer protected work hours or a more blended schedule?", defaultVisibility: "share", manualTemplate: "My availability works best when I can {answer}." },
      { id: "W_D_05", mode: "work", sectionId: "communication", depth: "deep", dimension: "Digital tone", type: "select", options: [option("brief", "Brief and direct", "brief and direct"), option("warm", "Warm and conversational", "warm and conversational"), option("structured", "Structured with bullets", "structured with bullets"), option("adaptive", "Matched to the situation", "matched to the situation")], label: "How would you describe your usual written work tone?", defaultVisibility: "share", manualTemplate: "My written work tone is usually {answer}." },
      { id: "W_D_06", mode: "work", sectionId: "execution", depth: "deep", dimension: "Deadlines", type: "select", options: [option("firm", "A deadline is firm unless renegotiated", "firm unless renegotiated"), option("signal", "A deadline is a signal to check scope", "a signal to check scope"), option("buffer", "I prefer buffer before the real due date", "buffer before the real due date"), option("depends", "I need the stakes named", "the stakes named")], label: "How do you relate to internal deadlines?", defaultVisibility: "share", manualTemplate: "For internal deadlines, I treat them as {answer}." },
      { id: "W_D_07", mode: "work", sectionId: "communication", depth: "deep", dimension: "Brainstorming", type: "pairedChoice", leftLabel: "Talk to think", rightLabel: "Think before speaking", label: "During a brainstorm, what helps your ideas show up?", defaultVisibility: "share", manualTemplate: "In brainstorms, I work best when I can {answer}." },
      { id: "W_D_08", mode: "work", sectionId: "culture", depth: "deep", dimension: "Trust", type: "select", options: [option("reliability", "Reliable follow-through", "reliable follow-through"), option("candor", "Clear candor", "clear candor"), option("time", "Time and consistency", "time and consistency"), option("small_wins", "Small wins together", "small wins together")], label: "How do you build trust with a new colleague?", defaultVisibility: "share", manualTemplate: "I build trust with new colleagues through {answer}." },
      { id: "W_D_09", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Interruptions", type: "scale", min: 1, max: 5, helperText: "1 = Quick reset, 5 = Slow reset", label: "How long does it take you to refocus after an unexpected interruption?", defaultVisibility: "share", manualTemplate: "After an unexpected interruption, my reset cost is around {answer} on a 1 to 5 scale." },
      { id: "W_D_10", mode: "work", sectionId: "communication", depth: "deep", dimension: "Listening cues", type: "textarea", label: "When you are listening intently, what might others notice?", defaultVisibility: "share", manualTemplate: "When I am listening intently, others may notice {answer}." },
      { id: "W_D_11", mode: "work", sectionId: "execution", depth: "deep", dimension: "Handoffs", type: "scale", min: 1, max: 5, helperText: "1 = High-level handoff, 5 = Detailed handoff", label: "When handing off a task, how much detail do you usually provide?", defaultVisibility: "share", manualTemplate: "My handoffs are around {answer} on a 1 to 5 detail scale." },
      { id: "W_D_12", mode: "work", sectionId: "culture", depth: "deep", dimension: "Motivation", type: "text", label: "What is the most meaningful compliment you have received at work?", defaultVisibility: "private", manualTemplate: "A meaningful work compliment for me was: {answer}." },
      { id: "W_D_13", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Capacity", type: "textarea", label: "What is the first sign that your capacity is getting too thin?", defaultVisibility: "private", manualTemplate: "The first sign my capacity is getting thin is {answer}." },
      { id: "W_D_14", mode: "work", sectionId: "execution", depth: "deep", dimension: "Meetings", type: "multiSelect", options: [option("no_decision", "No clear decision needed", "no clear decision needed"), option("no_context", "Missing context", "missing context"), option("too_many_people", "Too many people", "too many people"), option("no_owner", "No owner afterward", "no owner afterward")], label: "What makes a meeting feel like a poor use of time?", defaultVisibility: "share", manualTemplate: "Meetings feel like a poor use of time when there is {answer}." },
      { id: "W_D_15", mode: "work", sectionId: "culture", depth: "deep", dimension: "Group tension", type: "select", options: [option("mediate", "I try to clarify both sides", "try to clarify both sides"), option("step_back", "I step back", "step back"), option("solve", "I look for the practical next step", "look for the practical next step"), option("check_in", "I check in privately afterward", "check in privately afterward")], label: "When teammates are in tension, what role do you tend to take?", defaultVisibility: "private", manualTemplate: "When teammates are in tension, I tend to {answer}." },
      { id: "W_D_16", mode: "work", sectionId: "communication", depth: "deep", dimension: "Information format", type: "pairedChoice", leftLabel: "High-level summary", rightLabel: "Granular detail", label: "Do you prefer high-level summaries or granular details first?", defaultVisibility: "share", manualTemplate: "I prefer information to start with {answer}." },
      { id: "W_D_17", mode: "work", sectionId: "boundaries", depth: "deep", dimension: "Saying no", type: "scale", min: 1, max: 5, helperText: "1 = Easy to decline, 5 = Hard to decline", label: "How difficult is it for you to say no to a new project?", defaultVisibility: "private", manualTemplate: "Saying no to a new project is around {answer} on a 1 to 5 difficulty scale." },
      { id: "W_D_18", mode: "work", sectionId: "execution", depth: "deep", dimension: "Dependencies", type: "select", options: [option("track", "Track dependencies visibly", "track dependencies visibly"), option("trust", "Trust until there is a signal", "trust until there is a signal"), option("checkpoints", "Use agreed checkpoints", "use agreed checkpoints"), option("escalate", "Escalate blockers early", "escalate blockers early")], label: "How do you prefer to handle dependencies on others?", defaultVisibility: "share", manualTemplate: "For dependencies, I prefer to {answer}." },
      { id: "W_D_19", mode: "work", sectionId: "culture", depth: "deep", dimension: "Rapport", type: "pairedChoice", leftLabel: "Humor helps", rightLabel: "Keep it straightforward", label: "What kind of rapport feels natural at work?", defaultVisibility: "share", manualTemplate: "At work, rapport feels natural when we {answer}." },
      { id: "W_D_20", mode: "work", sectionId: "communication", depth: "deep", dimension: "Presentation format", type: "pairedChoice", leftLabel: "Diagrams or maps", rightLabel: "Written briefs", label: "Which format usually helps you understand a complex idea first?", defaultVisibility: "share", manualTemplate: "I usually understand complex ideas better through {answer}." },
      { id: "W_D_21", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Post-launch", type: "select", options: [option("rest", "A real pause", "a real pause"), option("retro", "A calm retro", "a calm retro"), option("next_steps", "Clear next steps", "clear next steps"), option("celebrate", "A moment to mark the work", "a moment to mark the work")], label: "After a major project ships, what do you need most?", defaultVisibility: "share", manualTemplate: "After a major project ships, I usually need {answer}." },
      { id: "W_D_22", mode: "work", sectionId: "communication", depth: "deep", dimension: "Upward feedback", type: "text", label: "How should a manager ask you for feedback on their own work?", defaultVisibility: "private", manualTemplate: "A manager can ask me for feedback by {answer}." },
      { id: "W_D_23", mode: "work", sectionId: "culture", depth: "deep", dimension: "Belonging", type: "textarea", label: "What makes you feel genuinely included in a team?", defaultVisibility: "share", manualTemplate: "I feel included in a team when {answer}." },
      { id: "W_D_24", mode: "work", sectionId: "culture", depth: "deep", dimension: "Mistakes", type: "text", label: "What helps a team talk about mistakes without blame?", defaultVisibility: "share", manualTemplate: "Teams talk about mistakes better when {answer}." },
    ],
  },
  talk: {
    id: "talk",
    name: "Conversation Manual",
    label: "How to talk with me",
    description: "Prepare a calmer conversation around what keeps getting missed.",
    theme: "talk",
    sections: [
      { id: "preparation", title: "Preparation", description: "What this conversation is for." },
      { id: "perspective", title: "Perspective", description: "What each person may be carrying." },
      { id: "message", title: "Message", description: "Facts, feelings, needs, and requests." },
      { id: "safety", title: "Safety", description: "How to keep the conversation usable." },
      { id: "followup", title: "Follow-up", description: "What happens after the talk." },
    ],
    questions: [
      { id: "T_M_01", mode: "talk", sectionId: "preparation", depth: "mvp", priority: 1, dimension: "Goal", type: "text", label: "What is your single most important goal for this conversation?", defaultVisibility: "share", manualTemplate: "My main goal for this conversation is {answer}." },
      { id: "T_M_02", mode: "talk", sectionId: "perspective", depth: "mvp", priority: 5, dimension: "Empathy", type: "textarea", label: "What do you think is the other person's most valid concern?", defaultVisibility: "private", manualTemplate: "I want to recognize that the other person's valid concern may be {answer}." },
      { id: "T_M_03", mode: "talk", sectionId: "message", depth: "mvp", priority: 2, dimension: "Observation", type: "textarea", label: "What are the exact facts of what happened, without adding judgment?", defaultVisibility: "private", manualTemplate: "The facts I want to name are {answer}." },
      { id: "T_M_04", mode: "talk", sectionId: "message", depth: "mvp", priority: 3, dimension: "Feeling", type: "text", label: "What did those facts bring up for you?", defaultVisibility: "private", manualTemplate: "What came up for me was {answer}." },
      { id: "T_M_05", mode: "talk", sectionId: "message", depth: "mvp", priority: 4, dimension: "Need", type: "text", label: "What need or value is underneath your reaction?", defaultVisibility: "private", manualTemplate: "The need or value underneath this is {answer}." },
      { id: "T_M_06", mode: "talk", sectionId: "message", depth: "mvp", priority: 6, dimension: "Request", type: "textarea", label: "What specific, actionable thing are you asking for?", defaultVisibility: "share", manualTemplate: "My request is {answer}." },
      { id: "T_M_07", mode: "talk", sectionId: "safety", depth: "mvp", priority: 7, dimension: "Misread patterns", type: "text", label: "What is the worst way they could misread your intent?", defaultVisibility: "private", manualTemplate: "I do not want my intent misread as {answer}." },
      { id: "T_M_08", mode: "talk", sectionId: "safety", depth: "mvp", priority: 8, dimension: "De-escalation", type: "textarea", label: "If the other person becomes defensive, what will you do to make the conversation safer?", defaultVisibility: "private", manualTemplate: "If defensiveness appears, I will try to {answer}." },
      { id: "T_M_09", mode: "talk", sectionId: "perspective", depth: "mvp", priority: 9, dimension: "Accountability", type: "textarea", label: "What is your own part in this situation?", defaultVisibility: "private", manualTemplate: "My own part in this situation is {answer}." },
      { id: "T_M_10", mode: "talk", sectionId: "safety", depth: "mvp", priority: 10, dimension: "Boundaries", type: "textarea", label: "If your request is not accepted, what boundary or next step would you choose?", defaultVisibility: "private", manualTemplate: "If my request is not accepted, my next step is {answer}." },
      { id: "T_M_11", mode: "talk", sectionId: "preparation", depth: "mvp", priority: 11, dimension: "Timing", type: "text", label: "When and where is the best time to have this conversation?", defaultVisibility: "share", manualTemplate: "The best time and place for this conversation is {answer}." },
      { id: "T_M_12", mode: "talk", sectionId: "followup", depth: "mvp", priority: 12, dimension: "Follow-up", type: "text", label: "How will you follow up after the conversation ends?", defaultVisibility: "share", manualTemplate: "After the conversation, I will follow up by {answer}." },
      { id: "T_D_01", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Story check", type: "textarea", label: "What story are you telling yourself about their motives?", defaultVisibility: "private", manualTemplate: "The story I am telling myself is {answer}." },
      { id: "T_D_02", mode: "talk", sectionId: "preparation", depth: "deep", dimension: "Shared purpose", type: "text", label: "What shared goal do you both care about?", defaultVisibility: "share", manualTemplate: "A shared goal we both care about is {answer}." },
      { id: "T_D_03", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Pressure", type: "textarea", label: "What pressure might they be under that you may not be seeing?", defaultVisibility: "private", manualTemplate: "They may be under pressure around {answer}." },
      { id: "T_D_04", mode: "talk", sectionId: "safety", depth: "deep", dimension: "Readiness", type: "text", label: "What does your body or attention tell you about your readiness right now?", defaultVisibility: "private", manualTemplate: "My readiness signal right now is {answer}." },
      { id: "T_D_05", mode: "talk", sectionId: "preparation", depth: "deep", dimension: "Scope", type: "pairedChoice", leftLabel: "A single event", rightLabel: "A recurring pattern", label: "Is this mostly a single event or a recurring pattern?", defaultVisibility: "share", manualTemplate: "This conversation is about {answer}." },
      { id: "T_D_06", mode: "talk", sectionId: "message", depth: "deep", dimension: "Tone", type: "text", label: "What tone do you want to bring into the conversation?", defaultVisibility: "share", manualTemplate: "The tone I want to bring is {answer}." },
      { id: "T_D_07", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Listening", type: "textarea", label: "What questions will you ask to understand their side?", defaultVisibility: "private", manualTemplate: "To understand their side, I can ask {answer}." },
      { id: "T_D_08", mode: "talk", sectionId: "safety", depth: "deep", dimension: "Strong emotion", type: "textarea", label: "If strong emotion appears, what immediate response would help you stay respectful?", defaultVisibility: "private", manualTemplate: "If strong emotion appears, I will try to {answer}." },
      { id: "T_D_09", mode: "talk", sectionId: "followup", depth: "deep", dimension: "Negotiation", type: "text", label: "What are you willing to be flexible about?", defaultVisibility: "private", manualTemplate: "I am willing to be flexible about {answer}." },
      { id: "T_D_10", mode: "talk", sectionId: "safety", depth: "deep", dimension: "Non-negotiable", type: "text", label: "What are you not willing to negotiate?", defaultVisibility: "private", manualTemplate: "I am not willing to negotiate {answer}." },
      { id: "T_D_11", mode: "talk", sectionId: "message", depth: "deep", dimension: "Careful opening", type: "textarea", label: "What truthful appreciation or respect can you include before the hard part?", defaultVisibility: "private", manualTemplate: "I can begin with this truthful appreciation: {answer}." },
      { id: "T_D_12", mode: "talk", sectionId: "message", depth: "deep", dimension: "Facts check", type: "pairedChoice", leftLabel: "Observable facts", rightLabel: "Interpretations mixed in", label: "Are your facts observable, or are interpretations mixed in?", defaultVisibility: "private", manualTemplate: "My facts check says: {answer}." },
      { id: "T_D_13", mode: "talk", sectionId: "message", depth: "deep", dimension: "Request check", type: "pairedChoice", leftLabel: "It is a request", rightLabel: "It may sound like a demand", label: "Does your request leave room for a real response?", defaultVisibility: "private", manualTemplate: "My request check says: {answer}." },
      { id: "T_D_14", mode: "talk", sectionId: "safety", depth: "deep", dimension: "Energy", type: "pairedChoice", leftLabel: "I have capacity now", rightLabel: "I should wait", label: "Do you have enough capacity to have this conversation now?", defaultVisibility: "private", manualTemplate: "My capacity check says: {answer}." },
      { id: "T_D_15", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Respect", type: "text", label: "What respect or care do you want them to feel from you?", defaultVisibility: "share", manualTemplate: "I want them to feel this respect or care: {answer}." },
      { id: "T_D_16", mode: "talk", sectionId: "followup", depth: "deep", dimension: "Outcome", type: "text", label: "What would a workable outcome look like for them?", defaultVisibility: "private", manualTemplate: "A workable outcome for them may look like {answer}." },
      { id: "T_D_17", mode: "talk", sectionId: "preparation", depth: "deep", dimension: "Trust context", type: "pairedChoice", leftLabel: "There is enough trust to talk", rightLabel: "Trust is already thin", label: "What is the trust context going into this conversation?", defaultVisibility: "private", manualTemplate: "The trust context is: {answer}." },
      { id: "T_D_18", mode: "talk", sectionId: "followup", depth: "deep", dimension: "Support", type: "text", label: "If the talk goes poorly, who or what will help you steady yourself afterward?", defaultVisibility: "private", manualTemplate: "If the talk goes poorly, I can steady myself with {answer}." },
      { id: "T_D_19", mode: "talk", sectionId: "message", depth: "deep", dimension: "Language check", type: "pairedChoice", leftLabel: "Mostly specific language", rightLabel: "Some sweeping language to revise", label: "Are you using specific language instead of sweeping claims?", defaultVisibility: "private", manualTemplate: "My language check says: {answer}." },
      { id: "T_D_20", mode: "talk", sectionId: "message", depth: "deep", dimension: "Pacing", type: "text", label: "How long will you speak before pausing for their response?", defaultVisibility: "share", manualTemplate: "I will pause for their response after {answer}." },
      { id: "T_D_21", mode: "talk", sectionId: "followup", depth: "deep", dimension: "Stakes", type: "text", label: "If no agreement is reached, what changes next?", defaultVisibility: "private", manualTemplate: "If no agreement is reached, the next change is {answer}." },
      { id: "T_D_22", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Active listening", type: "textarea", label: "How will you show that you are listening while they speak?", defaultVisibility: "share", manualTemplate: "I will show I am listening by {answer}." },
      { id: "T_D_23", mode: "talk", sectionId: "perspective", depth: "deep", dimension: "Outside view", type: "text", label: "What might a fair outside observer say about this situation?", defaultVisibility: "private", manualTemplate: "A fair outside observer might say {answer}." },
      { id: "T_D_24", mode: "talk", sectionId: "followup", depth: "deep", dimension: "Closure", type: "text", label: "How will you close the conversation with care, even if it is not fully resolved?", defaultVisibility: "share", manualTemplate: "I can close the conversation with care by {answer}." },
    ],
  },
  us: {
    id: "us",
    name: "Shared Manual",
    label: "How we understand each other",
    description: "Create a shared context note for two people trying to understand each other better.",
    theme: "us",
    sections: [
      { id: "rhythm", title: "Our rhythm", description: "How connection and daily life work between us." },
      { id: "care", title: "Care", description: "How support and bids for connection are noticed." },
      { id: "repair", title: "Repair", description: "How we pause, return, and make things right." },
      { id: "boundaries", title: "Boundaries", description: "Agreements that protect trust and privacy." },
      { id: "future", title: "Future", description: "Shared decisions, responsibilities, and direction." },
    ],
    questions: [
      { id: "U_M_01", mode: "us", sectionId: "rhythm", depth: "mvp", priority: 9, dimension: "Relationship rhythm", type: "select", options: [option("regular_checkins", "Regular check-ins", "regular check-ins"), option("space_then_return", "Space, then return", "space followed by return"), option("write_first", "Write first", "writing first"), option("live_talk", "Talk live", "talking live")], label: "What rhythm helps this relationship feel steady?", defaultVisibility: "share", manualTemplate: "We feel steadier when we use {answer}." },
      { id: "U_M_02", mode: "us", sectionId: "care", depth: "mvp", priority: 8, dimension: "Consideration", type: "multiSelect", options: [option("clear_plans", "Clear plans", "clear plans"), option("soft_starts", "Soft starts", "soft starts"), option("direct_honesty", "Direct honesty", "direct honesty"), option("time_to_respond", "Time to respond", "time to respond"), option("small_gestures", "Small gestures", "small gestures")], label: "What helps both of you feel considered?", defaultVisibility: "share", manualTemplate: "We both feel more considered with {answer}." },
      { id: "U_M_03", mode: "us", sectionId: "repair", depth: "mvp", priority: 5, dimension: "Misread patterns", type: "multiSelect", options: [option("silence", "Silence", "silence"), option("speed", "Speed", "speed"), option("tone", "Tone", "tone"), option("forgetfulness", "Forgetfulness", "forgetfulness"), option("space", "Needing space", "needing space")], label: "What gets misread most often between you?", defaultVisibility: "private", manualTemplate: "We should be careful not to over-read {answer}." },
      { id: "U_M_04", mode: "us", sectionId: "care", depth: "mvp", priority: 7, dimension: "Care", type: "textarea", label: "What should be understood with more care between you?", defaultVisibility: "private", manualTemplate: "A place where we need more care is {answer}." },
      { id: "U_M_05", mode: "us", sectionId: "repair", depth: "mvp", priority: 6, dimension: "Practice", type: "multiSelect", options: [option("ask_before_assuming", "Ask before assuming", "ask before assuming"), option("pause_before_replying", "Pause before replying", "pause before replying"), option("name_need", "Name the real need", "name the real need"), option("repair_sooner", "Repair sooner", "repair sooner"), option("smaller_plan", "Make a smaller plan", "make a smaller plan")], label: "What would be useful for both of you to practice?", defaultVisibility: "share", manualTemplate: "A useful practice for us is to {answer}." },
      { id: "U_M_06", mode: "us", sectionId: "future", depth: "mvp", priority: 1, dimension: "Shared responsibility", type: "select", options: [option("balanced", "It feels mostly balanced", "mostly balanced"), option("one_carries_more", "One of us carries more", "not evenly carried right now"), option("unclear", "We have not named it clearly", "not clearly named yet"), option("seasonal", "It changes by season", "seasonal and should be revisited")], label: "Between the two of you, how does the invisible planning and remembering feel right now?", defaultVisibility: "private", manualTemplate: "Our invisible planning and remembering feels {answer}." },
      { id: "U_M_07", mode: "us", sectionId: "repair", depth: "mvp", priority: 2, dimension: "Pause signal", type: "text", label: "When you are both overloaded, what agreed signal can pause the conversation?", defaultVisibility: "private", manualTemplate: "Our pause signal is {answer}." },
      { id: "U_M_08", mode: "us", sectionId: "boundaries", depth: "mvp", priority: 10, dimension: "Digital boundaries", type: "textarea", label: "What digital boundary would protect trust between you?", defaultVisibility: "private", manualTemplate: "A digital boundary that protects trust between us is {answer}." },
      { id: "U_M_09", mode: "us", sectionId: "repair", depth: "mvp", priority: 3, dimension: "Repair", type: "multiSelect", options: repairOptions, label: "After tension between you, what helps reconnection happen?", defaultVisibility: "private", manualTemplate: "After tension, reconnection is easier with {answer}." },
      { id: "U_M_10", mode: "us", sectionId: "care", depth: "mvp", priority: 4, dimension: "Bids for connection", type: "textarea", label: "What small bids for connection should each of you notice more often?", defaultVisibility: "private", manualTemplate: "Small bids for connection we should notice include {answer}." },
      { id: "U_M_11", mode: "us", sectionId: "boundaries", depth: "mvp", priority: 11, dimension: "Sharing boundaries", type: "textarea", label: "What information about this relationship should stay between you unless both agree?", defaultVisibility: "private", manualTemplate: "Information that should stay between us unless we both agree includes {answer}." },
      { id: "U_M_12", mode: "us", sectionId: "future", depth: "mvp", priority: 12, dimension: "Decision-making", type: "select", options: [option("talk_first", "Talk before deciding", "talk before deciding"), option("owner_decides", "The owner decides after input", "the owner deciding after input"), option("threshold", "Use a threshold for big decisions", "a threshold for big decisions"), option("trial", "Try it for a short time first", "a short trial first")], label: "How should you handle decisions that affect both of you?", defaultVisibility: "share", manualTemplate: "For decisions that affect both of us, we should use {answer}." },
      { id: "U_D_01", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Check-ins", type: "text", label: "What check-in cadence would help without making the relationship feel managed?", defaultVisibility: "share", manualTemplate: "A useful check-in cadence for us is {answer}." },
      { id: "U_D_02", mode: "us", sectionId: "care", depth: "deep", dimension: "Support", type: "multiSelect", options: supportOptions, label: "When one of you is struggling, what kind of support should the other offer first?", defaultVisibility: "share", manualTemplate: "When one of us is struggling, support can start with {answer}." },
      { id: "U_D_03", mode: "us", sectionId: "repair", depth: "deep", dimension: "Soft start", type: "text", label: "What opening sentence helps a hard topic start more gently?", defaultVisibility: "share", manualTemplate: "A useful opening sentence for hard topics is: {answer}." },
      { id: "U_D_04", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Phones", type: "textarea", label: "What are your rules about phones during meals, rest, or focused time?", defaultVisibility: "private", manualTemplate: "Our phone boundary for meals, rest, or focused time is {answer}." },
      { id: "U_D_05", mode: "us", sectionId: "future", depth: "deep", dimension: "Independence", type: "text", label: "Where would more independence help the relationship breathe?", defaultVisibility: "private", manualTemplate: "More independence would help around {answer}." },
      { id: "U_D_06", mode: "us", sectionId: "future", depth: "deep", dimension: "Values", type: "textarea", label: "What value difference needs respect rather than constant agreement?", defaultVisibility: "private", manualTemplate: "A value difference that needs respect is {answer}." },
      { id: "U_D_07", mode: "us", sectionId: "future", depth: "deep", dimension: "Family time", type: "textarea", label: "How should you approach time with families or important communities?", defaultVisibility: "private", manualTemplate: "For families or important communities, we should {answer}." },
      { id: "U_D_08", mode: "us", sectionId: "future", depth: "deep", dimension: "Tasks", type: "text", label: "What task or responsibility should be redistributed?", defaultVisibility: "private", manualTemplate: "A task or responsibility to redistribute is {answer}." },
      { id: "U_D_09", mode: "us", sectionId: "care", depth: "deep", dimension: "Closeness", type: "textarea", label: "How should you discuss intimacy or closeness without blame?", defaultVisibility: "private", manualTemplate: "We can discuss intimacy or closeness without blame by {answer}." },
      { id: "U_D_10", mode: "us", sectionId: "repair", depth: "deep", dimension: "Argument habits", type: "textarea", label: "What argument habit should each of you watch for with care?", defaultVisibility: "private", manualTemplate: "An argument habit for us to watch with care is {answer}." },
      { id: "U_D_11", mode: "us", sectionId: "care", depth: "deep", dimension: "Stress spillover", type: "select", options: [option("notice_fast", "Notice it quickly", "notice it quickly"), option("name_it", "Name it without blame", "name it without blame"), option("take_space", "Take space before continuing", "take space before continuing"), option("repair_after", "Repair afterward", "repair afterward")], label: "When stress spills into the relationship, what should happen first?", defaultVisibility: "private", manualTemplate: "When stress spills into the relationship, we should first {answer}." },
      { id: "U_D_12", mode: "us", sectionId: "care", depth: "deep", dimension: "Fun", type: "text", label: "What activity used to feel good together and may be worth bringing back?", defaultVisibility: "share", manualTemplate: "An activity worth bringing back is {answer}." },
      { id: "U_D_13", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Friends", type: "textarea", label: "How much detail about the relationship is okay to share with friends?", defaultVisibility: "private", manualTemplate: "With friends, it is okay to share {answer}." },
      { id: "U_D_14", mode: "us", sectionId: "future", depth: "deep", dimension: "Career", type: "textarea", label: "How should you handle seasons where one person's work needs more room?", defaultVisibility: "private", manualTemplate: "When one person's work needs more room, we should {answer}." },
      { id: "U_D_15", mode: "us", sectionId: "future", depth: "deep", dimension: "Money", type: "pairedChoice", leftLabel: "Save toward a named goal", rightLabel: "Keep more flexibility", label: "How are you approaching shared saving or spending right now?", defaultVisibility: "private", manualTemplate: "Our current money approach leans toward {answer}." },
      { id: "U_D_16", mode: "us", sectionId: "repair", depth: "deep", dimension: "Intent", type: "scale", min: 1, max: 5, helperText: "1 = We assume harm quickly, 5 = We check intent first", label: "When feelings are hurt, how easily do you check intent before reacting?", defaultVisibility: "private", manualTemplate: "When feelings are hurt, our intent-checking is around {answer} on a 1 to 5 scale." },
      { id: "U_D_17", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Routines", type: "textarea", label: "What routine creates daily friction, and what small adjustment would help?", defaultVisibility: "private", manualTemplate: "A daily routine we can adjust is {answer}." },
      { id: "U_D_18", mode: "us", sectionId: "future", depth: "deep", dimension: "Future", type: "textarea", label: "What would a good next year look like for both of you?", defaultVisibility: "share", manualTemplate: "A good next year for both of us would include {answer}." },
      { id: "U_D_19", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Privacy", type: "textarea", label: "What should each person be able to keep private without suspicion?", defaultVisibility: "private", manualTemplate: "Each person should be able to keep {answer} private without suspicion." },
      { id: "U_D_20", mode: "us", sectionId: "repair", depth: "deep", dimension: "Return plan", type: "text", label: "After a pause, how will you return to the conversation?", defaultVisibility: "share", manualTemplate: "After a pause, we will return by {answer}." },
      { id: "U_D_21", mode: "us", sectionId: "care", depth: "deep", dimension: "Reassurance", type: "text", label: "What reassurance helps when one person needs space?", defaultVisibility: "private", manualTemplate: "When one of us needs space, useful reassurance is {answer}." },
      { id: "U_D_22", mode: "us", sectionId: "future", depth: "deep", dimension: "Thresholds", type: "text", label: "What decision is big enough that both people should be consulted first?", defaultVisibility: "share", manualTemplate: "We should both be consulted before {answer}." },
      { id: "U_D_23", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Rest", type: "textarea", label: "How do you protect rest when life gets crowded?", defaultVisibility: "share", manualTemplate: "When life gets crowded, we protect rest by {answer}." },
      { id: "U_D_24", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Omitted is valid", type: "textarea", label: "What should be omitted from shared versions of this manual?", defaultVisibility: "hide", manualTemplate: "We prefer to omit {answer} from shared versions." },
    ],
  },
};
