/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Me Manual — "How to understand me"
 */

import type { ModeConfig } from "../schemaTypes";
import { option, supportOptions, repairOptions } from "./sharedOptions";

export const ME_MODE: ModeConfig = {
    id: "me",
    name: "Me Manual",
    label: "How to understand me",
    description: "Write the things people should know before they guess wrong.",
    theme: "me",
    sections: [
      { id: "connection", title: "Connection", description: "How care and attention reach me." },
      { id: "communication", title: "Communication", description: "How I process, ask, and respond." },
      { id: "boundaries", title: "Boundaries", description: "What helps closeness stay respectful." },
      { id: "tension", title: "Tension", description: "How to slow down and repair." },
      { id: "rhythm", title: "Rhythm", description: "Energy, attention, and everyday pacing." },
    ],
    questions: [
      { id: "M_M_01", mode: "me", sectionId: "connection", depth: "mvp", priority: 3, dimension: "Care and support", type: "multiSelect", options: supportOptions, label: "When you are going through a difficult time, what support actually helps?", defaultVisibility: "share", manualTemplate: "When I am having a difficult time, it helps if you {answer}." },
      { id: "M_M_02", mode: "me", sectionId: "tension", depth: "mvp", priority: 1, dimension: "Stress response", type: "select", options: [option("quiet", "I go quiet", "go quiet and need more room"), option("faster", "I talk faster", "talk faster and need us to slow down"), option("leave", "I need to step away", "need to step away before continuing"), option("explain", "I over-explain", "over-explain because I am trying to be understood")], label: "During a heated moment, what do you usually do when you feel overwhelmed?", defaultVisibility: "private", manualTemplate: "When I feel overwhelmed, I may {answer}." },
      { id: "M_M_03", mode: "me", sectionId: "tension", depth: "mvp", priority: 2, dimension: "Repair needs", type: "multiSelect", options: repairOptions, label: "After tension, what helps you feel ready to reconnect?", defaultVisibility: "private", manualTemplate: "After tension, reconnection is easier with {answer}." },
      { id: "M_M_04", mode: "me", sectionId: "rhythm", depth: "mvp", priority: 8, dimension: "Social energy", type: "select", options: [option("steady", "I stay steady for a long time", "extended time can feel steady for me"), option("selective", "I have energy for the right setting", "my energy depends on the setting"), option("shorter", "I do better with shorter time together", "shorter time together helps me stay present"), option("recover", "I need recovery time afterward", "I may need recovery time afterward")], label: "How does your energy usually work during extended time with friends or family?", defaultVisibility: "share", manualTemplate: "In extended time together, {answer}." },
      { id: "M_M_05", mode: "me", sectionId: "connection", depth: "mvp", priority: 5, dimension: "Connection bids", type: "text", label: "When you want attention or affection but have trouble asking, what might someone notice?", defaultVisibility: "private", manualTemplate: "When I want connection but have trouble asking, you might notice {answer}." },
      { id: "M_M_06", mode: "me", sectionId: "communication", depth: "mvp", priority: 6, dimension: "Misread patterns", type: "textarea", label: "What do people sometimes misread about you?", defaultVisibility: "private", manualTemplate: "People sometimes misread {answer}. Please ask before assuming." },
      { id: "M_M_07", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 9, dimension: "Digital boundaries", type: "select", options: [option("text_first", "Text first", "text first before calling"), option("calls_ok", "Calls are usually okay", "calls are usually okay"), option("urgent_only", "Call only for something time-sensitive", "call only for time-sensitive things"), option("ask_first", "Ask before calling", "ask before calling")], label: "How do you feel about unplanned phone calls from people close to you?", defaultVisibility: "share", manualTemplate: "For unplanned calls, please {answer}." },
      { id: "M_M_08", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 10, dimension: "Closeness and autonomy", type: "scale", min: 1, max: 5, helperText: "1 = More independent time, 5 = More shared time", label: "In close relationships, how much independent time versus shared time helps you feel steady?", defaultVisibility: "private", manualTemplate: "For independent time versus shared time, I am around {answer} on a 1 to 5 scale." },
      { id: "M_M_09", mode: "me", sectionId: "tension", depth: "mvp", priority: 7, dimension: "Pacing", type: "select", options: [option("same_day", "Usually the same day", "raise concerns the same day when possible"), option("after_time", "After I have had time", "need time before raising concerns"), option("written", "I write first", "often write before talking"), option("hard_to_raise", "I find it hard to raise", "may need an invitation to name concerns")], label: "When someone close to you does something upsetting, how soon do you usually bring it up?", defaultVisibility: "private", manualTemplate: "When something upsets me, I usually {answer}." },
      { id: "M_M_10", mode: "me", sectionId: "communication", depth: "mvp", priority: 4, dimension: "Processing style", type: "select", options: [option("write_first", "Write first", "write first"), option("talk_live", "Talk it through live", "talk it through live"), option("pause", "Pause before answering", "pause before answering"), option("question_first", "Start with one clear question", "start with one clear question")], label: "When something matters, how do you prefer to process it?", defaultVisibility: "share", manualTemplate: "When something matters, I process best when I can {answer}." },
      { id: "M_M_11", mode: "me", sectionId: "boundaries", depth: "mvp", priority: 11, dimension: "Consent and boundaries", type: "textarea", label: "What is one boundary that helps you stay open instead of guarded?", defaultVisibility: "private", manualTemplate: "One boundary that helps me stay open is {answer}." },
      { id: "M_M_12", mode: "me", sectionId: "connection", depth: "mvp", priority: 12, dimension: "Care expression", type: "multiSelect", options: [option("check_ins", "Small check-ins", "small check-ins"), option("practical_care", "Practical care", "practical care"), option("quality_time", "Focused time", "focused time"), option("thoughtful_words", "Thoughtful words", "thoughtful words"), option("respecting_space", "Respecting my space", "respecting my space")], label: "How do you most naturally notice that someone cares?", defaultVisibility: "share", manualTemplate: "I tend to notice care through {answer}." },
      { id: "M_D_01", mode: "me", sectionId: "connection", depth: "deep", dimension: "Support", type: "textarea", label: "What kind of help can feel well-meant but unhelpful?", defaultVisibility: "private", manualTemplate: "Well-meant help can be unhelpful when {answer}." },
      { id: "M_D_02", mode: "me", sectionId: "tension", depth: "deep", dimension: "Repair needs", type: "text", label: "If someone breaks a small promise, what helps make it right?", defaultVisibility: "private", manualTemplate: "If a small promise is broken, repair looks like {answer}." },
      { id: "M_D_03", mode: "me", sectionId: "communication", depth: "deep", dimension: "Directness", type: "pairedChoice", leftLabel: "Tell me plainly", rightLabel: "Warm me up first", label: "When something is difficult to hear, what helps it land?", defaultVisibility: "share", manualTemplate: "Difficult things land better when the approach is {answer}." },
      { id: "M_D_04", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Digital boundaries", type: "textarea", label: "What digital boundary would help people respect your attention?", defaultVisibility: "share", manualTemplate: "A digital boundary that helps me is {answer}." },
      { id: "M_D_05", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Recovery", type: "select", options: [option("quiet", "Quiet time", "quiet time"), option("movement", "Movement or a reset walk", "movement or a reset walk"), option("sleep", "Sleep or a full stop", "sleep or a full stop"), option("normal_routine", "A normal routine", "a normal routine")], label: "After a demanding day, what helps you come back to yourself?", defaultVisibility: "private", manualTemplate: "After a demanding day, I usually need {answer}." },
      { id: "M_D_06", mode: "me", sectionId: "communication", depth: "deep", dimension: "Listening cues", type: "textarea", label: "When you are listening carefully, what might your body language look like?", defaultVisibility: "share", manualTemplate: "When I am listening carefully, I may look like {answer}." },
      { id: "M_D_07", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Topic boundaries", type: "textarea", label: "What topic or setting needs extra permission before someone goes there with you?", defaultVisibility: "private", manualTemplate: "Please ask before bringing up {answer}." },
      { id: "M_D_08", mode: "me", sectionId: "connection", depth: "deep", dimension: "Appreciation", type: "text", label: "What is a small gesture that means more to you than people realize?", defaultVisibility: "share", manualTemplate: "A small gesture that means a lot to me is {answer}." },
      { id: "M_D_09", mode: "me", sectionId: "tension", depth: "deep", dimension: "Pause signals", type: "text", label: "What phrase could someone use when they notice the conversation needs to slow down?", defaultVisibility: "private", manualTemplate: "If we need to slow down, it helps to say: {answer}." },
      { id: "M_D_10", mode: "me", sectionId: "communication", depth: "deep", dimension: "Clarity", type: "multiSelect", options: [option("examples", "Specific examples", "specific examples"), option("one_topic", "One topic at a time", "one topic at a time"), option("plain_request", "A plain request", "a plain request"), option("time_to_reply", "Time to reply", "time to reply")], label: "What helps you understand a sensitive message clearly?", defaultVisibility: "share", manualTemplate: "Sensitive messages are easier for me with {answer}." },
      { id: "M_D_11", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Social pacing", type: "scale", min: 1, max: 5, helperText: "1 = Plans need notice, 5 = Spontaneous plans are easy", label: "How much notice helps you say yes to plans?", defaultVisibility: "share", manualTemplate: "For plans, my notice preference is around {answer} on a 1 to 5 scale." },
      { id: "M_D_12", mode: "me", sectionId: "connection", depth: "deep", dimension: "Receiving care", type: "textarea", label: "What makes care feel respectful rather than intrusive?", defaultVisibility: "private", manualTemplate: "Care feels respectful when {answer}." },
      { id: "M_D_13", mode: "me", sectionId: "tension", depth: "deep", dimension: "Accountability", type: "textarea", label: "When you need to apologize, what helps you do it honestly?", defaultVisibility: "private", manualTemplate: "When I need to apologize, it helps if {answer}." },
      { id: "M_D_14", mode: "me", sectionId: "communication", depth: "deep", dimension: "Assumptions", type: "textarea", label: "What should people ask about before they decide what your silence means?", defaultVisibility: "private", manualTemplate: "Before deciding what my silence means, please ask about {answer}." },
      { id: "M_D_15", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Physical boundaries", type: "textarea", label: "What personal-space preference should someone know before they try to comfort you?", defaultVisibility: "private", manualTemplate: "For personal space, it helps to know {answer}." },
      { id: "M_D_16", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Attention", type: "pairedChoice", leftLabel: "I like parallel time", rightLabel: "I like focused attention", label: "When spending time together, what kind of presence feels best?", defaultVisibility: "share", manualTemplate: "Time together feels best with {answer}." },
      { id: "M_D_17", mode: "me", sectionId: "connection", depth: "deep", dimension: "Requests", type: "text", label: "What is something you often need but forget to ask for?", defaultVisibility: "private", manualTemplate: "Something I may need but forget to ask for is {answer}." },
      { id: "M_D_18", mode: "me", sectionId: "communication", depth: "deep", dimension: "Tone", type: "textarea", label: "What tone helps you stay open during disagreement?", defaultVisibility: "share", manualTemplate: "During disagreement, I stay more open with {answer}." },
      { id: "M_D_19", mode: "me", sectionId: "tension", depth: "deep", dimension: "Repair timing", type: "select", options: [option("immediate", "Soon after", "soon after"), option("same_day", "Later the same day", "later the same day"), option("next_day", "After a night of rest", "after a night of rest"), option("scheduled", "At a planned time", "at a planned time")], label: "When repair is needed, what timing usually works best?", defaultVisibility: "private", manualTemplate: "Repair usually works best {answer}." },
      { id: "M_D_20", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Sharing boundaries", type: "textarea", label: "What should someone check with you before sharing about you with others?", defaultVisibility: "private", manualTemplate: "Please check with me before sharing {answer}." },
      { id: "M_D_21", mode: "me", sectionId: "rhythm", depth: "deep", dimension: "Transitions", type: "text", label: "What helps you transition from alone time into connection?", defaultVisibility: "share", manualTemplate: "I transition into connection more easily with {answer}." },
      { id: "M_D_22", mode: "me", sectionId: "connection", depth: "deep", dimension: "Encouragement", type: "textarea", label: "What kind of encouragement feels steadying instead of pressuring?", defaultVisibility: "share", manualTemplate: "Encouragement feels steadying when {answer}." },
      { id: "M_D_23", mode: "me", sectionId: "communication", depth: "deep", dimension: "Repair language", type: "text", label: "What sentence helps you feel someone is still with you during a hard talk?", defaultVisibility: "private", manualTemplate: "During a hard talk, it helps to hear: {answer}." },
      { id: "M_D_24", mode: "me", sectionId: "boundaries", depth: "deep", dimension: "Omitted is valid", type: "textarea", label: "What is something you prefer to keep out of a shared manual?", defaultVisibility: "hide", manualTemplate: "I prefer to omit {answer} from shared versions." },
    ],
};
