/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Shared Manual — "How we understand each other"
 */

import type { ModeConfig } from "../schemaTypes";
import { option, supportOptions, repairOptions } from "./sharedOptions";

export const US_MODE: ModeConfig = {
    id: "us",
    name: "Shared Manual",
    label: "How we understand each other",
    description: "Create a shared context note for two people trying to understand each other better.",
    theme: "us",
    sections: [
      { id: "rhythm", title: "Our rhythm", description: "How connection and daily life work between us." },
      { id: "care", title: "Care", description: "How support and bids for connection are noticed." },
      { id: "repair", title: "Repair", description: "How we pause, return, and make things right." },
      { id: "boundaries", title: "Boundaries", description: "Agreements that protect trust and privacy." },
      { id: "future", title: "Future", description: "Shared decisions, responsibilities, and direction." },
    ],
    questions: [
      { id: "U_M_01", mode: "us", sectionId: "rhythm", depth: "mvp", priority: 9, dimension: "Relationship rhythm", type: "select", options: [option("regular_checkins", "Regular check-ins", "regular check-ins"), option("space_then_return", "Space, then return", "space followed by return"), option("write_first", "Write first", "writing first"), option("live_talk", "Talk live", "talking live")], label: "What rhythm helps this relationship feel steady?", defaultVisibility: "share", manualTemplate: "We feel steadier when we use {answer}." },
      { id: "U_M_02", mode: "us", sectionId: "care", depth: "mvp", priority: 8, dimension: "Consideration", type: "multiSelect", options: [option("clear_plans", "Clear plans", "clear plans"), option("soft_starts", "Soft starts", "soft starts"), option("direct_honesty", "Direct honesty", "direct honesty"), option("time_to_respond", "Time to respond", "time to respond"), option("small_gestures", "Small gestures", "small gestures")], label: "What helps both of you feel considered?", defaultVisibility: "share", manualTemplate: "We both feel more considered with {answer}." },
      { id: "U_M_03", mode: "us", sectionId: "repair", depth: "mvp", priority: 5, dimension: "Misread patterns", type: "multiSelect", options: [option("silence", "Silence", "silence"), option("speed", "Speed", "speed"), option("tone", "Tone", "tone"), option("forgetfulness", "Forgetfulness", "forgetfulness"), option("space", "Needing space", "needing space")], label: "What gets misread most often between you?", defaultVisibility: "private", manualTemplate: "We should be careful not to over-read {answer}." },
      { id: "U_M_04", mode: "us", sectionId: "care", depth: "mvp", priority: 7, dimension: "Care", type: "textarea", label: "What should be understood with more care between you?", defaultVisibility: "private", manualTemplate: "A place where we need more care is {answer}." },
      { id: "U_M_05", mode: "us", sectionId: "repair", depth: "mvp", priority: 6, dimension: "Practice", type: "multiSelect", options: [option("ask_before_assuming", "Ask before assuming", "ask before assuming"), option("pause_before_replying", "Pause before replying", "pause before replying"), option("name_need", "Name the real need", "name the real need"), option("repair_sooner", "Repair sooner", "repair sooner"), option("smaller_plan", "Make a smaller plan", "make a smaller plan")], label: "What would be useful for both of you to practice?", defaultVisibility: "share", manualTemplate: "A useful practice for us is to {answer}." },
      { id: "U_M_06", mode: "us", sectionId: "future", depth: "mvp", priority: 1, dimension: "Shared responsibility", type: "select", options: [option("balanced", "It feels mostly balanced", "mostly balanced"), option("one_carries_more", "One of us carries more", "not evenly carried right now"), option("unclear", "We have not named it clearly", "not clearly named yet"), option("seasonal", "It changes by season", "seasonal and should be revisited")], label: "Between the two of you, how does the invisible planning and remembering feel right now?", defaultVisibility: "private", manualTemplate: "Our invisible planning and remembering feels {answer}." },
      { id: "U_M_07", mode: "us", sectionId: "repair", depth: "mvp", priority: 2, dimension: "Pause signal", type: "text", label: "When you are both overloaded, what agreed signal can pause the conversation?", defaultVisibility: "private", manualTemplate: "Our pause signal is {answer}." },
      { id: "U_M_08", mode: "us", sectionId: "boundaries", depth: "mvp", priority: 10, dimension: "Digital boundaries", type: "textarea", label: "What digital boundary would protect trust between you?", defaultVisibility: "private", manualTemplate: "A digital boundary that protects trust between us is {answer}." },
      { id: "U_M_09", mode: "us", sectionId: "repair", depth: "mvp", priority: 3, dimension: "Repair", type: "multiSelect", options: repairOptions, label: "After tension between you, what helps reconnection happen?", defaultVisibility: "private", manualTemplate: "After tension, reconnection is easier with {answer}." },
      { id: "U_M_10", mode: "us", sectionId: "care", depth: "mvp", priority: 4, dimension: "Bids for connection", type: "textarea", label: "What small bids for connection should each of you notice more often?", defaultVisibility: "private", manualTemplate: "Small bids for connection we should notice include {answer}." },
      { id: "U_M_11", mode: "us", sectionId: "boundaries", depth: "mvp", priority: 11, dimension: "Sharing boundaries", type: "textarea", label: "What information about this relationship should stay between you unless both agree?", defaultVisibility: "private", manualTemplate: "Information that should stay between us unless we both agree includes {answer}." },
      { id: "U_M_12", mode: "us", sectionId: "future", depth: "mvp", priority: 12, dimension: "Decision-making", type: "select", options: [option("talk_first", "Talk before deciding", "talk before deciding"), option("owner_decides", "The owner decides after input", "the owner deciding after input"), option("threshold", "Use a threshold for big decisions", "a threshold for big decisions"), option("trial", "Try it for a short time first", "a short trial first")], label: "How should you handle decisions that affect both of you?", defaultVisibility: "share", manualTemplate: "For decisions that affect both of us, we should use {answer}." },
      { id: "U_D_01", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Check-ins", type: "text", label: "What check-in cadence would help without making the relationship feel managed?", defaultVisibility: "share", manualTemplate: "A useful check-in cadence for us is {answer}." },
      { id: "U_D_02", mode: "us", sectionId: "care", depth: "deep", dimension: "Support", type: "multiSelect", options: supportOptions, label: "When one of you is struggling, what kind of support should the other offer first?", defaultVisibility: "share", manualTemplate: "When one of us is struggling, support can start with {answer}." },
      { id: "U_D_03", mode: "us", sectionId: "repair", depth: "deep", dimension: "Soft start", type: "text", label: "What opening sentence helps a hard topic start more gently?", defaultVisibility: "share", manualTemplate: "A useful opening sentence for hard topics is: {answer}." },
      { id: "U_D_04", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Phones", type: "textarea", label: "What are your rules about phones during meals, rest, or focused time?", defaultVisibility: "private", manualTemplate: "Our phone boundary for meals, rest, or focused time is {answer}." },
      { id: "U_D_05", mode: "us", sectionId: "future", depth: "deep", dimension: "Independence", type: "text", label: "Where would more independence help the relationship breathe?", defaultVisibility: "private", manualTemplate: "More independence would help around {answer}." },
      { id: "U_D_06", mode: "us", sectionId: "future", depth: "deep", dimension: "Values", type: "textarea", label: "What value difference needs respect rather than constant agreement?", defaultVisibility: "private", manualTemplate: "A value difference that needs respect is {answer}." },
      { id: "U_D_07", mode: "us", sectionId: "future", depth: "deep", dimension: "Family time", type: "textarea", label: "How should you approach time with families or important communities?", defaultVisibility: "private", manualTemplate: "For families or important communities, we should {answer}." },
      { id: "U_D_08", mode: "us", sectionId: "future", depth: "deep", dimension: "Tasks", type: "text", label: "What task or responsibility should be redistributed?", defaultVisibility: "private", manualTemplate: "A task or responsibility to redistribute is {answer}." },
      { id: "U_D_09", mode: "us", sectionId: "care", depth: "deep", dimension: "Closeness", type: "textarea", label: "How should you discuss intimacy or closeness without blame?", defaultVisibility: "private", manualTemplate: "We can discuss intimacy or closeness without blame by {answer}." },
      { id: "U_D_10", mode: "us", sectionId: "repair", depth: "deep", dimension: "Argument habits", type: "textarea", label: "What argument habit should each of you watch for with care?", defaultVisibility: "private", manualTemplate: "An argument habit for us to watch with care is {answer}." },
      { id: "U_D_11", mode: "us", sectionId: "care", depth: "deep", dimension: "Stress spillover", type: "select", options: [option("notice_fast", "Notice it quickly", "notice it quickly"), option("name_it", "Name it without blame", "name it without blame"), option("take_space", "Take space before continuing", "take space before continuing"), option("repair_after", "Repair afterward", "repair afterward")], label: "When stress spills into the relationship, what should happen first?", defaultVisibility: "private", manualTemplate: "When stress spills into the relationship, we should first {answer}." },
      { id: "U_D_12", mode: "us", sectionId: "care", depth: "deep", dimension: "Fun", type: "text", label: "What activity used to feel good together and may be worth bringing back?", defaultVisibility: "share", manualTemplate: "An activity worth bringing back is {answer}." },
      { id: "U_D_13", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Friends", type: "textarea", label: "How much detail about the relationship is okay to share with friends?", defaultVisibility: "private", manualTemplate: "With friends, it is okay to share {answer}." },
      { id: "U_D_14", mode: "us", sectionId: "future", depth: "deep", dimension: "Career", type: "textarea", label: "How should you handle seasons where one person's work needs more room?", defaultVisibility: "private", manualTemplate: "When one person's work needs more room, we should {answer}." },
      { id: "U_D_15", mode: "us", sectionId: "future", depth: "deep", dimension: "Money", type: "pairedChoice", leftLabel: "Save toward a named goal", rightLabel: "Keep more flexibility", label: "How are you approaching shared saving or spending right now?", defaultVisibility: "private", manualTemplate: "Our current money approach leans toward {answer}." },
      { id: "U_D_16", mode: "us", sectionId: "repair", depth: "deep", dimension: "Intent", type: "scale", min: 1, max: 5, helperText: "1 = We assume harm quickly, 5 = We check intent first", label: "When feelings are hurt, how easily do you check intent before reacting?", defaultVisibility: "private", manualTemplate: "When feelings are hurt, our intent-checking is around {answer} on a 1 to 5 scale." },
      { id: "U_D_17", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Routines", type: "textarea", label: "What routine creates daily friction, and what small adjustment would help?", defaultVisibility: "private", manualTemplate: "A daily routine we can adjust is {answer}." },
      { id: "U_D_18", mode: "us", sectionId: "future", depth: "deep", dimension: "Future", type: "textarea", label: "What would a good next year look like for both of you?", defaultVisibility: "share", manualTemplate: "A good next year for both of us would include {answer}." },
      { id: "U_D_19", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Privacy", type: "textarea", label: "What should each person be able to keep private without suspicion?", defaultVisibility: "private", manualTemplate: "Each person should be able to keep {answer} private without suspicion." },
      { id: "U_D_20", mode: "us", sectionId: "repair", depth: "deep", dimension: "Return plan", type: "text", label: "After a pause, how will you return to the conversation?", defaultVisibility: "share", manualTemplate: "After a pause, we will return by {answer}." },
      { id: "U_D_21", mode: "us", sectionId: "care", depth: "deep", dimension: "Reassurance", type: "text", label: "What reassurance helps when one person needs space?", defaultVisibility: "private", manualTemplate: "When one of us needs space, useful reassurance is {answer}." },
      { id: "U_D_22", mode: "us", sectionId: "future", depth: "deep", dimension: "Thresholds", type: "text", label: "What decision is big enough that both people should be consulted first?", defaultVisibility: "share", manualTemplate: "We should both be consulted before {answer}." },
      { id: "U_D_23", mode: "us", sectionId: "rhythm", depth: "deep", dimension: "Rest", type: "textarea", label: "How do you protect rest when life gets crowded?", defaultVisibility: "share", manualTemplate: "When life gets crowded, we protect rest by {answer}." },
      { id: "U_D_24", mode: "us", sectionId: "boundaries", depth: "deep", dimension: "Omitted is valid", type: "textarea", label: "What should be omitted from shared versions of this manual?", defaultVisibility: "hide", manualTemplate: "We prefer to omit {answer} from shared versions." },
    ],
};
