/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Work Manual — "How to work with me"
 */

import type { ModeConfig } from "../schemaTypes";
import { option, directnessOptions } from "./sharedOptions";

export const WORK_MODE: ModeConfig = {
    id: "work",
    name: "Work Manual",
    label: "How to work with me",
    description: "Share how you focus, decide, talk, and build trust.",
    theme: "work",
    sections: [
      { id: "communication", title: "Communication", description: "How information and feedback land best." },
      { id: "execution", title: "Execution", description: "How work moves from idea to done." },
      { id: "boundaries", title: "Boundaries", description: "Availability, attention, and handoff limits." },
      { id: "pressure", title: "Pressure", description: "Stress, urgency, and support." },
      { id: "culture", title: "Culture", description: "Trust, recognition, and team fit." },
    ],
    questions: [
      { id: "W_M_01", mode: "work", sectionId: "communication", depth: "mvp", priority: 4, dimension: "Processing style", type: "select", options: [option("pre_read", "A pre-read before live discussion", "a pre-read before live discussion"), option("live", "A live conversation", "a live conversation"), option("written", "A written brief", "a written brief"), option("hybrid", "A short brief, then a live check-in", "a short brief, then a live check-in")], label: "When dealing with complex new information, how do you prefer to digest it?", defaultVisibility: "share", manualTemplate: "For complex new information, please use {answer}." },
      { id: "W_M_02", mode: "work", sectionId: "communication", depth: "mvp", priority: 2, dimension: "Directness and context", type: "select", options: directnessOptions, label: "If there is a flaw in your idea, how should a teammate bring it up?", defaultVisibility: "share", manualTemplate: "If there is a flaw in my idea, feedback lands best as {answer}." },
      { id: "W_M_03", mode: "work", sectionId: "execution", depth: "mvp", priority: 9, dimension: "Autonomy and closeness", type: "select", options: [option("autonomy", "Give me the goal and room to own it", "a clear goal with room to own the path"), option("milestones", "Agree on milestones and check-ins", "milestones and check-ins"), option("collaborative", "Work closely with me as it takes shape", "close collaboration while it takes shape"), option("clear_brief", "Give me a detailed brief first", "a detailed brief before I start")], label: "What collaboration style helps you do your best work?", defaultVisibility: "share", manualTemplate: "I do my best work with {answer}." },
      { id: "W_M_04", mode: "work", sectionId: "boundaries", depth: "mvp", priority: 12, dimension: "Digital boundaries", type: "select", options: [option("next_day", "I will respond next working day", "respond next working day"), option("read_not_reply", "I may read, but not reply", "may read but not reply"), option("urgent_only", "Only urgent items need a response", "respond only when it is urgent"), option("clear_marker", "Mark urgency clearly", "need urgency marked clearly")], label: "How do you treat non-urgent digital messages outside working hours?", defaultVisibility: "share", manualTemplate: "For non-urgent messages outside working hours, I usually {answer}." },
      { id: "W_M_05", mode: "work", sectionId: "pressure", depth: "mvp", priority: 6, dimension: "Stress signals", type: "multiSelect", options: [option("quiet", "I get quieter", "get quieter"), option("rigid", "I get more rigid", "get more rigid"), option("overcommunicate", "I overcommunicate", "overcommunicate"), option("slow_reply", "I reply more slowly", "reply more slowly"), option("narrow_focus", "I narrow my focus", "narrow my focus")], label: "What is your most common behavioral tell when you are overwhelmed at work?", defaultVisibility: "private", manualTemplate: "When I am overwhelmed at work, I may {answer}." },
      { id: "W_M_06", mode: "work", sectionId: "pressure", depth: "mvp", priority: 7, dimension: "Care and support", type: "select", options: [option("prioritize", "Help me prioritize", "help me prioritize"), option("remove_blocker", "Remove or clarify a blocker", "remove or clarify a blocker"), option("quiet_space", "Give me quiet space", "give me quiet space"), option("check_capacity", "Ask what capacity I have", "ask what capacity I have")], label: "When that stress tell appears, what is the most useful response from a colleague?", defaultVisibility: "private", manualTemplate: "When that stress tell appears, the most useful response is to {answer}." },
      { id: "W_M_07", mode: "work", sectionId: "execution", depth: "mvp", priority: 10, dimension: "Attention and focus", type: "select", options: [option("long_blocks", "Long quiet blocks", "long quiet blocks"), option("short_sprints", "Short focused sprints", "short focused sprints"), option("meeting_days", "Meeting days and focus days separated", "meeting days and focus days separated"), option("flexible", "Flexible around the work", "flexible around the work")], label: "How do you prefer to structure your daily focus?", defaultVisibility: "share", manualTemplate: "My focus works best with {answer}." },
      { id: "W_M_08", mode: "work", sectionId: "communication", depth: "mvp", priority: 11, dimension: "Urgency and escalation", type: "text", label: "What is the best way to interrupt you for a genuine time-sensitive emergency?", defaultVisibility: "share", manualTemplate: "For a genuine time-sensitive emergency, reach me by {answer}." },
      { id: "W_M_09", mode: "work", sectionId: "culture", depth: "mvp", priority: 8, dimension: "Misread patterns", type: "textarea", label: "What is a common way your working style is misunderstood by people who do not know you well?", defaultVisibility: "private", manualTemplate: "People may misunderstand my working style as {answer}. Please ask before assuming." },
      { id: "W_M_10", mode: "work", sectionId: "execution", depth: "mvp", priority: 5, dimension: "Decision-making", type: "select", options: [option("data", "Clear data or examples", "clear data or examples"), option("owner", "A named decision owner", "a named decision owner"), option("consensus", "Enough group alignment", "enough group alignment"), option("reversible", "Knowing whether it is reversible", "knowing whether the decision is reversible")], label: "When a team decision needs to be made, what helps you move forward?", defaultVisibility: "share", manualTemplate: "I can move forward on team decisions when there is {answer}." },
      { id: "W_M_11", mode: "work", sectionId: "culture", depth: "mvp", priority: 11, dimension: "Recognition", type: "select", options: [option("private", "Private appreciation", "private appreciation"), option("public", "Public credit", "public credit"), option("specific", "Specific feedback on the work", "specific feedback on the work"), option("opportunity", "A meaningful next opportunity", "a meaningful next opportunity")], label: "When you do excellent work, how do you prefer to be recognized?", defaultVisibility: "share", manualTemplate: "Recognition is most meaningful to me as {answer}." },
      { id: "W_M_12", mode: "work", sectionId: "communication", depth: "mvp", priority: 3, dimension: "Meeting energy", type: "scale", min: 1, max: 5, helperText: "1 = Draining quickly, 5 = Usually energizing", label: "How do back-to-back video meetings usually affect your energy?", defaultVisibility: "share", manualTemplate: "Back-to-back video meetings affect my energy around {answer} on a 1 to 5 scale." },
      { id: "W_D_01", mode: "work", sectionId: "communication", depth: "deep", dimension: "Psychological safety", type: "textarea", label: "If you need to push back on leadership, what makes it feel possible to speak honestly?", defaultVisibility: "private", manualTemplate: "I can push back more honestly when {answer}." },
      { id: "W_D_02", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Accountability", type: "select", options: [option("fix_then_flag", "Bring the issue with a proposed fix", "bring the issue with a proposed fix"), option("flag_fast", "Flag it quickly", "flag it quickly"), option("ask_help", "Ask for help early", "ask for help early"), option("document", "Document what happened", "document what happened")], label: "When you make a mistake, what helps you handle it well?", defaultVisibility: "private", manualTemplate: "When I make a mistake, I handle it best when I can {answer}." },
      { id: "W_D_03", mode: "work", sectionId: "execution", depth: "deep", dimension: "Ambiguity", type: "select", options: [option("ask_questions", "Ask clarifying questions", "ask clarifying questions"), option("draft_options", "Draft options and get direction", "draft options and get direction"), option("start_small", "Start with a small version", "start with a small version"), option("pause", "Pause until the brief is clearer", "pause until the brief is clearer")], label: "How do you behave when project requirements are vague?", defaultVisibility: "share", manualTemplate: "When requirements are vague, I tend to {answer}." },
      { id: "W_D_04", mode: "work", sectionId: "boundaries", depth: "deep", dimension: "Availability", type: "pairedChoice", leftLabel: "Protect set hours", rightLabel: "Blend flexibly", label: "Do you prefer protected work hours or a more blended schedule?", defaultVisibility: "share", manualTemplate: "My availability works best when I can {answer}." },
      { id: "W_D_05", mode: "work", sectionId: "communication", depth: "deep", dimension: "Digital tone", type: "select", options: [option("brief", "Brief and direct", "brief and direct"), option("warm", "Warm and conversational", "warm and conversational"), option("structured", "Structured with bullets", "structured with bullets"), option("adaptive", "Matched to the situation", "matched to the situation")], label: "How would you describe your usual written work tone?", defaultVisibility: "share", manualTemplate: "My written work tone is usually {answer}." },
      { id: "W_D_06", mode: "work", sectionId: "execution", depth: "deep", dimension: "Deadlines", type: "select", options: [option("firm", "A deadline is firm unless renegotiated", "firm unless renegotiated"), option("signal", "A deadline is a signal to check scope", "a signal to check scope"), option("buffer", "I prefer buffer before the real due date", "buffer before the real due date"), option("depends", "I need the stakes named", "the stakes named")], label: "How do you relate to internal deadlines?", defaultVisibility: "share", manualTemplate: "For internal deadlines, I treat them as {answer}." },
      { id: "W_D_07", mode: "work", sectionId: "communication", depth: "deep", dimension: "Brainstorming", type: "pairedChoice", leftLabel: "Talk to think", rightLabel: "Think before speaking", label: "During a brainstorm, what helps your ideas show up?", defaultVisibility: "share", manualTemplate: "In brainstorms, I work best when I can {answer}." },
      { id: "W_D_08", mode: "work", sectionId: "culture", depth: "deep", dimension: "Trust", type: "select", options: [option("reliability", "Reliable follow-through", "reliable follow-through"), option("candor", "Clear candor", "clear candor"), option("time", "Time and consistency", "time and consistency"), option("small_wins", "Small wins together", "small wins together")], label: "How do you build trust with a new colleague?", defaultVisibility: "share", manualTemplate: "I build trust with new colleagues through {answer}." },
      { id: "W_D_09", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Interruptions", type: "scale", min: 1, max: 5, helperText: "1 = Quick reset, 5 = Slow reset", label: "How long does it take you to refocus after an unexpected interruption?", defaultVisibility: "share", manualTemplate: "After an unexpected interruption, my reset cost is around {answer} on a 1 to 5 scale." },
      { id: "W_D_10", mode: "work", sectionId: "communication", depth: "deep", dimension: "Listening cues", type: "textarea", label: "When you are listening intently, what might others notice?", defaultVisibility: "share", manualTemplate: "When I am listening intently, others may notice {answer}." },
      { id: "W_D_11", mode: "work", sectionId: "execution", depth: "deep", dimension: "Handoffs", type: "scale", min: 1, max: 5, helperText: "1 = High-level handoff, 5 = Detailed handoff", label: "When handing off a task, how much detail do you usually provide?", defaultVisibility: "share", manualTemplate: "My handoffs are around {answer} on a 1 to 5 detail scale." },
      { id: "W_D_12", mode: "work", sectionId: "culture", depth: "deep", dimension: "Motivation", type: "text", label: "What is the most meaningful compliment you have received at work?", defaultVisibility: "private", manualTemplate: "A meaningful work compliment for me was: {answer}." },
      { id: "W_D_13", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Capacity", type: "textarea", label: "What is the first sign that your capacity is getting too thin?", defaultVisibility: "private", manualTemplate: "The first sign my capacity is getting thin is {answer}." },
      { id: "W_D_14", mode: "work", sectionId: "execution", depth: "deep", dimension: "Meetings", type: "multiSelect", options: [option("no_decision", "No clear decision needed", "no clear decision needed"), option("no_context", "Missing context", "missing context"), option("too_many_people", "Too many people", "too many people"), option("no_owner", "No owner afterward", "no owner afterward")], label: "What makes a meeting feel like a poor use of time?", defaultVisibility: "share", manualTemplate: "Meetings feel like a poor use of time when there is {answer}." },
      { id: "W_D_15", mode: "work", sectionId: "culture", depth: "deep", dimension: "Group tension", type: "select", options: [option("mediate", "I try to clarify both sides", "try to clarify both sides"), option("step_back", "I step back", "step back"), option("solve", "I look for the practical next step", "look for the practical next step"), option("check_in", "I check in privately afterward", "check in privately afterward")], label: "When teammates are in tension, what role do you tend to take?", defaultVisibility: "private", manualTemplate: "When teammates are in tension, I tend to {answer}." },
      { id: "W_D_16", mode: "work", sectionId: "communication", depth: "deep", dimension: "Information format", type: "pairedChoice", leftLabel: "High-level summary", rightLabel: "Granular detail", label: "Do you prefer high-level summaries or granular details first?", defaultVisibility: "share", manualTemplate: "I prefer information to start with {answer}." },
      { id: "W_D_17", mode: "work", sectionId: "boundaries", depth: "deep", dimension: "Saying no", type: "scale", min: 1, max: 5, helperText: "1 = Easy to decline, 5 = Hard to decline", label: "How difficult is it for you to say no to a new project?", defaultVisibility: "private", manualTemplate: "Saying no to a new project is around {answer} on a 1 to 5 difficulty scale." },
      { id: "W_D_18", mode: "work", sectionId: "execution", depth: "deep", dimension: "Dependencies", type: "select", options: [option("track", "Track dependencies visibly", "track dependencies visibly"), option("trust", "Trust until there is a signal", "trust until there is a signal"), option("checkpoints", "Use agreed checkpoints", "use agreed checkpoints"), option("escalate", "Escalate blockers early", "escalate blockers early")], label: "How do you prefer to handle dependencies on others?", defaultVisibility: "share", manualTemplate: "For dependencies, I prefer to {answer}." },
      { id: "W_D_19", mode: "work", sectionId: "culture", depth: "deep", dimension: "Rapport", type: "pairedChoice", leftLabel: "Humor helps", rightLabel: "Keep it straightforward", label: "What kind of rapport feels natural at work?", defaultVisibility: "share", manualTemplate: "At work, rapport feels natural when we {answer}." },
      { id: "W_D_20", mode: "work", sectionId: "communication", depth: "deep", dimension: "Presentation format", type: "pairedChoice", leftLabel: "Diagrams or maps", rightLabel: "Written briefs", label: "Which format usually helps you understand a complex idea first?", defaultVisibility: "share", manualTemplate: "I usually understand complex ideas better through {answer}." },
      { id: "W_D_21", mode: "work", sectionId: "pressure", depth: "deep", dimension: "Post-launch", type: "select", options: [option("rest", "A real pause", "a real pause"), option("retro", "A calm retro", "a calm retro"), option("next_steps", "Clear next steps", "clear next steps"), option("celebrate", "A moment to mark the work", "a moment to mark the work")], label: "After a major project ships, what do you need most?", defaultVisibility: "share", manualTemplate: "After a major project ships, I usually need {answer}." },
      { id: "W_D_22", mode: "work", sectionId: "communication", depth: "deep", dimension: "Upward feedback", type: "text", label: "How should a manager ask you for feedback on their own work?", defaultVisibility: "private", manualTemplate: "A manager can ask me for feedback by {answer}." },
      { id: "W_D_23", mode: "work", sectionId: "culture", depth: "deep", dimension: "Belonging", type: "textarea", label: "What makes you feel genuinely included in a team?", defaultVisibility: "share", manualTemplate: "I feel included in a team when {answer}." },
      { id: "W_D_24", mode: "work", sectionId: "culture", depth: "deep", dimension: "Mistakes", type: "text", label: "What helps a team talk about mistakes without blame?", defaultVisibility: "share", manualTemplate: "Teams talk about mistakes better when {answer}." },
    ],
};
